# Generated by Django 3.1.7 on 2021-04-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(choices=[('df', 'DF'), ('sp', 'SP'), ('rj', 'RJ')], max_length=60, verbose_name='state'),
        ),
    ]
