# Generated by Django 3.1.7 on 2021-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210410_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=60, verbose_name='state'),
        ),
    ]
