# Generated by Django 3.1.7 on 2021-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='store_instagram_report',
            field=models.CharField(default=1, max_length=100, verbose_name='Loja denunciada'),
            preserve_default=False,
        ),
    ]
