# Generated by Django 3.1.7 on 2021-04-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvaliationCreate',
            new_name='Avaliation',
        ),
    ]
