# Generated by Django 3.1.7 on 2021-04-13 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliation',
            name='likes',
            field=models.ManyToManyField(related_name='avaliations', to=settings.AUTH_USER_MODEL),
        ),
    ]
