# Generated by Django 3.1.7 on 2021-04-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='deliveryTime',
        ),
    ]
