# Generated by Django 3.1.7 on 2021-04-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='description',
            field=models.TextField(verbose_name='Conte sobre o produto'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='entregaRapida',
            field=models.IntegerField(choices=[(1, 'estrela1'), (2, 'estrela2'), (3, 'estrela3'), (4, 'estrela4'), (5, 'estrela5')], verbose_name='Velocidade da Entrega'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='nomeProduto',
            field=models.CharField(max_length=25, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='user_instagram',
            field=models.CharField(max_length=25, verbose_name='Instagram Avaliado(Ex:@lojinha)'),
        ),
    ]
