# Generated by Django 3.1.7 on 2021-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='ratingAvaliation',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
