# Generated by Django 3.1.7 on 2021-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_auto_20210419_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='rating',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='ratingAvaliation',
            field=models.IntegerField(default=1),
        ),
    ]
