# Generated by Django 3.1.7 on 2021-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_auto_20210420_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='ratingAvaliation',
            field=models.IntegerField(default=1),
        ),
    ]
