# Generated by Django 3.1.7 on 2021-04-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_auto_20210405_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='user_instagram',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='categoria',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='entregaRapida',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('ótimo', 'Ótimo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='nomeProduto',
            field=models.CharField(max_length=25),
        ),
    ]
