# Generated by Django 3.1.7 on 2021-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_auto_20210410_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliation',
            name='notaAvaliacao',
            field=models.IntegerField(choices=[(1, 'estrela1'), (2, 'estrela2'), (3, 'estrela3'), (4, 'estrela4'), (5, 'estrela5')], default=1, verbose_name='Nota de Avaliação'),
            preserve_default=False,
        ),
    ]
