# Generated by Django 3.1.7 on 2021-05-03 22:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_auto_20210427_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
