# Generated by Django 3.1.7 on 2021-04-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_avaliation_likes'),
        ('avaliations', '0003_avaliation_notaavaliacao'),
    ]

    operations = [
    ]
