# Generated by Django 3.1.7 on 2021-04-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0003_auto_20210419_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliation',
            old_name='ratingAvaliation',
            new_name='rating',
        ),
    ]
