# Generated by Django 3.1.7 on 2021-04-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0003_auto_20210405_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='categoria',
            field=models.CharField(choices=[('autos_e_pecas', 'Autos e Peças'), ('para_sua_casa', 'Para a Sua Casa'), ('eletronicos_e_celulares', 'Eletrônicos e celulares'), ('musica_e_hobbies', 'Musicas e Hobbies'), ('artigos_infatis', 'Artigos Infantis'), ('moda_e_beleza', 'Moda e Beleza'), ('animais_de_estimacao', 'Animais de Estimação'), ('servicos', 'Serviços'), ('agro_e_industrias', 'Agro e Industrias'), ('esportes_e_lazer', 'Esportes e Lazer'), ('comercio_e_escritorio', 'Comercio e Escritorio')], max_length=25),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='entregaRapida',
            field=models.IntegerField(choices=[(1, 'estrela1'), (2, 'estrela2'), (3, 'estrela3'), (4, 'estrela4'), (5, 'estrela5')]),
        ),
    ]
