# Generated by Django 3.1.7 on 2021-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0004_merge_20210415_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliation',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='avaliation',
            name='entregaRapida',
        ),
        migrations.RemoveField(
            model_name='avaliation',
            name='nomeProduto',
        ),
        migrations.RemoveField(
            model_name='avaliation',
            name='notaAvaliacao',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='deliveryTime',
            field=models.IntegerField(choices=[(1, 'star1'), (2, 'star2'), (3, 'star3'), (4, 'star4'), (5, 'star5')], default=1, verbose_name='Velocidade da Entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliation',
            name='ratingAvaliation',
            field=models.IntegerField(choices=[(1, 'star1'), (2, 'star2'), (3, 'star3'), (4, 'star4'), (5, 'star5')], default=1, verbose_name='Nota de Avaliação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliation',
            name='titleAvaliation',
            field=models.CharField(default=1, max_length=100, verbose_name='Titulo do Produto'),
            preserve_default=False,
        ),
    ]
