# Generated by Django 3.1.7 on 2021-04-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0004_auto_20210426_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliation',
            old_name='rating',
            new_name='ratingAvaliation',
        ),
    ]
